dns_tools/dns/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('sites.urls')),
]

dns_tools/sites/urls.py
from django.urls import path, include
from . import views

app_name='sites'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('menu/', views.zones_menu, name='menu'),
    path('rr_search/', views.rr_search, name='search'),
    path('rr_get/<int:id>/', views.rr_get, name='get'),
    path('zones/', views.zones, name='data'),
    path('rr_op/', views.rr_op, name='op'),
    path('rr_add/', views.rr_add, name='add'),
    path('rr_edit/<int:id>/', views.rr_edit, name='edit'),
    path('flush_rr/',views.flush_rr,name='flush'),
]

dns_tools/sites/models.py
from django.db import models


# Create your models here.

class DnsToolBindrr(models.Model):
    type = models.CharField(max_length=12, blank=True, null=True)
    domain_name = models.CharField(max_length=100, blank=True, null=True)
    priority = models.CharField(max_length=20, blank=True, null=True)
    value = models.CharField(max_length=100, blank=True, null=True)
    disabled_flag = models.IntegerField()
    reversed_flag = models.IntegerField()
    last_modified_date = models.DateTimeField()
    last_modified_user = models.CharField(max_length=40, blank=True, null=True)
    related_to_id = models.IntegerField(unique=True, blank=True, null=True)
    zone = models.ForeignKey('DnsToolBindzones', models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return '%s %s %s %s' % (self.zone.zone_name, self.domain_name, self.type, self.value)

    class Meta:
        db_table = 'dns_tool_bindrr'
        unique_together = (('type', 'domain_name', 'value', 'zone'),)


class DnsToolBindzones(models.Model):
    zone_name = models.CharField(max_length=90, blank=True, null=True)
    serial_num = models.CharField(max_length=20, blank=True, null=True)
    start_part = models.TextField(blank=True, null=True)
    type = models.CharField(max_length=10, blank=True, null=True)
    city = models.CharField(max_length=3, blank=True, null=True)
    parent_to = models.ForeignKey('self', models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return '%s %s' % (self.zone_name, self.city)

    class Meta:
        db_table = 'dns_tool_bindzones'


class DnsRrs(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    type = models.CharField(max_length=12, blank=True, null=True)
    value = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=3, blank=True, null=True)
    zone_name = models.CharField(max_length=90, blank=True, null=True)
    zone_id = models.IntegerField(blank=True, null=True)
    direction = models.CharField(max_length=10, blank=True, null=True)
    disabled_flag = models.IntegerField()
    reversed_flag = models.IntegerField()
    user = models.CharField(max_length=40, blank=True, null=True)
    date = models.DateTimeField()

    class Meta:
        managed = False  # Created from a view. Don't remove.
        db_table = 'dns_rrs'

    def toJSON1(self):
        import json

        return json.dumps(dict([(attr, getattr(self, attr)) for attr in [f.name for f in self._meta.fields]]))

    def toJSON(self):
        fields = []
        import datetime
        for field in self._meta.fields:
            fields.append(field.name)

        d = {}
        for attr in fields:
            if isinstance(getattr(self, attr), datetime.datetime):
                d[attr] = getattr(self, attr).strftime('%Y-%m-%d %H:%M:%S')
            elif isinstance(getattr(self, attr), datetime.date):
                d[attr] = getattr(self, attr).strftime('%Y-%m-%d')
            else:
                d[attr] = getattr(self, attr)

        import json
        return json.dumps(d)

dns_tools/sites/forms.py
from django import forms
from .models import DnsToolBindzones

query_city=DnsToolBindzones.objects.using("dns").filter(type='Forward').values('city').distinct()
CITY=[]
for c in query_city:
    CITY.append((c['city'],c['city']))
# query_zone=DnsToolBindzones.objects.filter(type='Forward').values('city','zone_name','parent_to').order_by('-parent_to')
query_zone=DnsToolBindzones.objects.using("dns").filter(type='Forward').values('city','zone_name','parent_to').order_by('parent_to')
ZONE={}
for i in query_zone:
    ZONE.setdefault(i['city'],[]).append((i['zone_name'],i['zone_name']))
CNAME=CITY

class addForm(forms.Form):
    name = forms.CharField(max_length=100,required=True)
    type = forms.ChoiceField(widget=forms.Select,choices=[('A','A'),('CNAME','CNAME')])
    value = forms.CharField(max_length=100,required=True)
    city = forms.ChoiceField(widget=forms.Select, choices=CITY)
    zone_name = forms.ChoiceField(widget=forms.Select, choices=ZONE)
    cname = forms.ChoiceField(widget=forms.CheckboxSelectMultiple,choices=CNAME)
    disabled_flag = forms.BooleanField(required=False)
    reversed_flag = forms.BooleanField(required=False)

dns_tools/sites/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from dns.LdapBackend import LDAPBackend
from dwebsocket.decorators import accept_websocket, require_websocket


def check_login(fn):
    def wrapper(request, *args, **kwargs):
        # request.session.clear()
        request.session.clear_expired()
        print(request.session.get_expiry_date())
        if request.session.get('is_login_dns_username', False):
            return fn(request, *args, *kwargs)
        else:
            return redirect('sites:login')

    return wrapper


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = LDAPBackend().authenticate(username, password)
        print(username, password, user)
        if user:
            request.session['is_login_dns_username'] = True
            request.session.set_expiry(86400)
            request.session['username'] = username
            return redirect('sites:index')
        else:
            return render(request, 'login.html', {'notify': 'authentication failed'})
    else:
        request.session.clear_expired()
        if request.session.get('is_login_dns_username', False):
            return redirect('sites:index')
        return render(request, 'login.html')

def logout(request):
    request.session.clear_expired()
    request.session.flush()
    return redirect('sites:login')

# Create your views here.
@check_login
def index(request):
    username=request.session.get('username',False)
    return render(request, 'index.html', context=locals())


# init
def zones_menu(request):
    from .models import DnsToolBindzones
    zones = DnsToolBindzones.objects.using("dns").filter(type='Forward').order_by('parent_to_id', 'city').values('id',
                                                                                                                 'zone_name',
                                                                                                                 'city',
                                                                                                                 'parent_to')
    # print(zones.query)
    result = []
    result_name = []
    for item in list(zones):
        # print(item)
        if item['parent_to'] == None and item['zone_name'] not in result_name:
            result_name.append(item['zone_name'])
            result.append(
                {'id': item['zone_name'], 'parent': '#', 'text': item['zone_name'], 'state': {'opened': True}})
            result.append({'id': item['id'], 'parent': item['zone_name'], 'text': item['city']})
        elif item['zone_name'] in result_name:
            result.append({'id': item['id'], 'parent': item['zone_name'], 'text': item['city']})
        else:
            result.append({'id': item['id'], 'parent': item['parent_to'], 'text': item['zone_name']})
    return JsonResponse(result, safe=False)


def str_to_bool(str):
    return True if str.lower() == 'true' else False


def rr_search(request):
    import json
    from .models import DnsRrs, DnsToolBindzones
    from django.db.models import Q
    from django.core.paginator import Paginator
    from django.core import serializers
    direction = request.GET.get('direction', 'Forward')
    zone_name = request.GET.get('zone_name', 'com')
    zone_id = request.GET.get('zone_id', 0)
    search_text = request.GET.get('search', 0)
    filter = request.GET.get('filter', {})
    fuzzy = str_to_bool(request.GET.get('fuzzy', 'True'))
    sort = request.GET.get('sort', 'name')
    sort_order = request.GET.get('order', 'asc')
    if sort_order == 'asc':
        rrs = DnsRrs.objects.using("dns").filter(Q(direction=direction)).order_by('%s' % sort)
    else:
        rrs = DnsRrs.objects.using("dns").filter(Q(direction=direction)).order_by('-%s' % sort)
    # print(fuzzy,type(fuzzy))
    if not zone_id:
        rrs = rrs.filter(Q(zone_name__icontains=zone_name))
    else:
        child_zone_names = DnsToolBindzones.objects.using("dns").filter(parent_to=zone_id).values('zone_name')
        rrs = rrs.filter((Q(zone_name__in=child_zone_names) | Q(zone_id=zone_id)))
    if search_text and fuzzy:
        rrs = rrs.filter((Q(name__icontains=search_text) | Q(value__icontains=search_text)))
    elif search_text and not fuzzy:
        rrs = rrs.filter((Q(name=search_text) | Q(value=search_text)))
    if filter: filter = json.loads(filter)
    for k, v in filter.items():
        if k == 'type':
            rrs = rrs.filter(type=v)
        elif k == 'zone':
            rrs = rrs.filter(zone_name__icontains='.'.join(v.split('.')[:-1]))
            rrs = rrs.filter(city=v.split('.')[-1])
        elif k == 'name' and fuzzy:
            rrs = rrs.filter(name__icontains=v)
        elif k == 'name' and not fuzzy:
            print(1)
            rrs = rrs.filter(name=v)
        elif k == 'value' and fuzzy:
            rrs = rrs.filter(value__icontains=v)
        else:
            rrs = rrs.filter(value=v)
    page_limit = request.GET.get('limit', 15)
    page_offset = request.GET.get('offset', 0)
    if not page_offset:
        page = 1
    else:
        page = int(int(page_offset) / int(page_limit) + 1)
    paginator = Paginator(rrs, page_limit)
    rrs_page = paginator.get_page(page)
    query_result = serializers.serialize('json', rrs_page,
                                         fields=('id', 'city', 'zone_name', 'name', 'type', 'value',
                                                 'disabled_flag', 'reversed_flag', 'user', 'date'))
    result = {}
    # print(query_result)
    # json -> list, get need data
    rrs_count = rrs.count()
    result['total'] = rrs_count
    result['totalNotFilteredField'] = rrs_count
    result['pageNumber'] = page
    result['rows'] = []
    import json
    for rr in json.loads(query_result):
        rr['fields']['id'] = rr['pk']
        rr['fields']['zone'] = rr['fields']['zone_name'] + '.' + rr['fields']['city']
        result['rows'].append(rr['fields'])
    return HttpResponse(json.dumps(result))


def zones(request):
    from .forms import CITY, ZONE
    city = request.GET.get('city', False)
    if city:
        Zone = ZONE[city]
    else:
        Zone = ZONE
    return JsonResponse(Zone, safe=False)


def rr_get(request, id):
    from .models import DnsRrs
    rrs = DnsRrs.objects.using('dns').get(id=id)
    return HttpResponse(rrs.toJSON())


@check_login
@csrf_exempt
def rr_op(request):
    if request.method == 'GET':
        action = request.GET.get('action', '')
        if action == 'add':
            from .forms import addForm
            Form = addForm()
            return render(request, 'initform.html', locals())
        elif action == 'del':
            ids = request.GET.getlist('ids[]', None)
            # print(ids)
            from .models import DnsToolBindrr
            from django.db.models import Q
            DnsToolBindrr.objects.using("dns").filter(Q(id__in=ids)).delete()
            return HttpResponse(1)
        elif action == 'edit':
            from .forms import addForm as editFrom
            id = request.GET.get('id', '')
            Form = editFrom()
            # print(id)
            return render(request, 'initform.html', locals())
        elif action == 'flush':
            return render(request, 'flush.html')
        else:
            return HttpResponse('no Action')


def check_value(value):
    if value.split('.')[-1]: value += '.'
    return value


@csrf_exempt
def rr_add(request):
    if request.method == 'POST':
        from .models import DnsToolBindrr, DnsToolBindzones
        query_zone = DnsToolBindzones.objects.using("dns").filter(type='Forward').values('id', 'city', 'zone_name',
                                                                                         'parent_to').order_by(
            'parent_to')
        zones = {}
        for i in query_zone:
            zones.setdefault(i['city'], {}).setdefault(i['zone_name'], {})
            zones[i['city']][i['zone_name']] = {'id': i['id'], 'parent_to': i['parent_to']}

        import datetime
        name = request.POST.get('name', '')
        type = request.POST.get('type', '')
        value = request.POST.get('value', '')
        city = request.POST.get('city', '')
        zone_name = request.POST.get('zone_name', '')
        cname = request.POST.getlist('cname', '')
        disabled_flag = request.POST.get('disabled_flag', 0)
        if disabled_flag == 'on': disabled_flag = 1
        reversed_flag = request.POST.get('reversed_flag', 0)
        if reversed_flag == 'on': reversed_flag = 1
        user = request.session.get('username','test')
        update_date = datetime.datetime.now(tz=datetime.timezone(datetime.timedelta(hours=8)))
        # print(name, type, value, city, zone_name, cname, disabled_flag, reversed_flag, user, update_date)
        # print(zones)
        rrs = {}
        if type == 'CNAME': value = check_value(value)
        new_rr = DnsToolBindrr(domain_name=name, type=type, priority=None, value=value, disabled_flag=disabled_flag,
                               reversed_flag=reversed_flag, last_modified_date=update_date, last_modified_user=user,
                               related_to_id=None,
                               zone=DnsToolBindzones.objects.using("dns").get(id=zones[city][zone_name]['id']))
        new_rr.save()
        if zones[city][zone_name]['parent_to']:
            for c in cname:
                zone_parent_name = DnsToolBindzones.objects.using("dns").get(
                    id=zones[city][zone_name]['parent_to']).zone_name
                print(zone_name, zone_parent_name, c)
                cname_value = name + '.' + zone_name
                cname_value = check_value(cname_value)

dns_tools/sites/templates/flush.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>flush records</title>
    <script src="{{ static('jquery.min.js') }}"></script>
    <script type="text/javascript">
        var socket = new WebSocket("ws://" + window.location.host + "/flush_rr/");
        console.log(socket);
        socket.onopen = function () {
            socket.send('flush_rr');//发送数据到服务端
        };
        socket.onmessage = function (e) {
            $('#messagecontainer').append(e.data+'<br/>');
            wd=document.body.clientHeight;
            window.scroll({top:wd,left:0,behavior:'smooth'});
        };

    </script>
    <style>
        pre{
            word-wrap: break-word;
            margin: 0;
            display: block;
            font-family: monospace;
        }

    </style>
</head>
<body>
<div style="margin: 20px;">
    <pre id="messagecontainer" class="console-output">
    </pre>
</div>
</body>
</html>

dns_tools/sites/templates/index.html
{% extends 'base.html' %}
{% block title %} DNS_Tools——BootstrapTable{% endblock %}
{% block css %}
    {#    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">#}
    {#    <link href="https://cdn.bootcss.com/bootstrap-table/1.15.4/bootstrap-table.min.css" rel="stylesheet">#}
    {#    <link href="https://cdn.bootcss.com/bootstrap-table/1.15.4/extensions/filter-control/bootstrap-table-filter-control.min.css"#}
    {#          rel="stylesheet">#}
    {#    <link href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" rel="stylesheet">#}
    {#    <link href="https://cdn.bootcss.com/jstree/3.3.8/themes/default/style.min.css" rel="stylesheet">#}
    <link href="{{ static('bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ static('bootstrap-table.min.css') }}" rel="stylesheet">
    <link href="{{ static('bootstrap-table-filter-control.min.css') }}" rel="stylesheet">
    <link href="{{ static('all.css') }}" rel="stylesheet">
    <link href="{{ static('style.min.css') }}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <link rel="stylesheet" href="{{ static('index.css') }}">
{% endblock %}

{% block body %}
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">DNS_Tools</a>
        {#        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">#}
        {#        <ul class="navbar-nav px-3">#}
        {#            <li class="nav-item text-nowrap">#}
        {#                <a class="nav-link" href="#">Sign out</a>#}
        {#            </li>#}
        {#        </ul>#}
        <div style="float:right;color:#fff;">
            {{ username }}
            <button id="logout" class="btn btn-secondary btn-xs" onclick="location.href='{{ url('sites:logout') }}'">Logout</button>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <div id="sidebar"></div>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                <div id="toolbar">
                    <button id="add_rr" class="btn btn-secondary">Add</button>
                    <button id="edit_rr" class="btn btn-secondary">Edit</button>
                    <button id="del_rr" class="btn btn-secondary">Del</button>
                    <button id="flush_rr" class="btn btn-secondary">Flush</button>
                </div>
                <table id="table_data">
                </table>
            </main>
        </div>
    </div>
{% endblock %}
{% block js_body %}
    {#    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>#}
    {#    <script src="https://cdn.bootcss.com/popper.js/1.14.6/umd/popper.min.js"></script>#}
    {#    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>#}
    {#    <script src="https://cdn.bootcss.com/bootstrap-table/1.15.4/bootstrap-table.min.js"></script>#}
    {#    <script src="https://cdn.bootcss.com/bootstrap-table/1.15.4/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>#}
    {#    <script src="https://cdn.bootcss.com/bootstrap-table/1.15.4/extensions/editable/bootstrap-table-editable.min.js"></script>#}
    {#    <script src="https://cdn.bootcss.com/jstree/3.3.8/jstree.min.js"></script>#}

    <script src="{{ static('jquery.min.js') }}"></script>
    <script src="{{ static('popper.min.js') }}"></script>
    <script src="{{ static('bootstrap.min.js') }}"></script>
    <script src="{{ static('bootstrap-table.min.js') }}"></script>
    <script src="{{ static('bootstrap-table-filter-control.min.js') }}"></script>
    <script src="{{ static('layer.min.js') }}"></script>
    <script src="{{ static('jstree.min.js') }}"></script>

    <script src="{{ static('jquerysession.js') }}"></script>
    <script src="{{ static('index.js') }}"></script>
{% endblock %}

dns_tools/sites/templates/initform.html
{% extends "base.html" %}
{% block css %}
    <link href="{{ static('bootstrap.min.css') }}" rel="stylesheet">
    <style>
        ul {
            list-style-type: none;
            padding: 0;
            margin: 0
        }

        ul li {
            display: inline-table;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="container">
        <div class="col">
            {% if action == 'edit' %}
            <form id="form_op" class="form-horizontal" action="/rr_{{ action }}/{{id}}/" method="post">
            {% else %}
            <form id="form_op" class="form-horizontal" action="/rr_{{ action }}/" method="post">
            {% endif %}
                <table>
                    {{ Form.as_table() }}
                </table>
                <div>
                    <button type="submit" class="btn btn-primary float-right">Submit</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block js_body %}
        <script src="{{ static('jquery.min.js') }}"></script>
        <script src="{{ static('popper.min.js') }}"></script>
        <script src="{{ static('bootstrap.min.js') }}"></script>
    <script>
        // css
        $('#id_name').addClass('form-control');
        $('#id_type').addClass('form-control');
        $('#id_value').addClass('form-control');
        $('#id_city').addClass('form-control');
        $('#id_zone_name').addClass('form-control');


        function change_zones(zones, city) {
            if (!city) {
                var city = $('#id_city').val();
            }
            $('#id_zone_name').empty()
            for (i in zones[city]) {
                $('#id_zone_name').append('<option value="' + zones[city][i][0] + '">' + zones[city][i][0] + '</option>')
            }
        }

        var zones;
        $.get('/zones/', function (data) {
            change_zones(data);
            zones = data;
        });


        // city and zone_name

        $('#id_city').change(function () {
            change_zones(zones);
        });


        // id = document.location.pathname.match('.*/([0-9]+)/$')[1];   //   /rr_op/61047243/
        id=document.location.search.match('.*=([0-9]+)$')[1]           // /rr_op/?action=edit&id=61047243
        if (id) {
            $.get('/rr_get/' + id + '/', function (data) {
                r = JSON.parse(data);
                $('#id_name').val(r.name);
                $('#id_value').val(r.value);
                $('#id_type').find("option[value='" + r.type + "']").attr("selected", true);
                $('#id_city').find("option[value='" + r.city + "']").attr("selected", true);
                change_zones(zones, r.city);
                $('#id_zone_name').find("option[value='" + r.zone_name + "']").attr("selected", true);
                $('#id_city').attr("disabled","disabled");
                $('#id_zone_name').attr("disabled","disabled");
                $('#id_disabled_flag').attr("disabled","disabled");
                $('#id_reversed_flag').attr("disabled","disabled");
            })
        }
    </script>
{% endblock %}